Control server UDP packet obfuscation
ghmo2789/puppet-master pull request #113
Opened 2022-12-07 08:52 UTC by Rickebo

Adds obfuscation to UDP packets by XOR-ing contents with a predefined key. Fixes #112.

2022-12-07 08:58 UTC, ghmo2789 approved these changes
Looks good.

2022-12-12 10:33 UTC, ghmo2789 requested changes
It would be nice to have smaller PR but the changes looks good. Maybe it is a good idea to update the README with the new information regarding UDP connection.

2022-12-12 16:45 UTC, ghmo2789 approved these changes
Looks good.

2022-12-13 10:49 UTC, johanlovgren approved these changes

2022-12-13 10:49 UTC, merged