Client UDP compression
ghmo2789/puppet-master pull request #119
Opened 2022-12-09 12:42 UTC by johanlovgren

Solves #118

2022-12-12 10:02 UTC, Rickebo approved these changes
Looks good!

2022-12-12 10:03 UTC, Rickebo requested changes
Perhaps failing tests should be fixed or removed

2022-12-12 14:35 UTC, ghmo2789 approved these changes

2022-12-13 16:50 UTC, Rickebo approved these changes

2022-12-13 16:50 UTC, merged